//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishGuide
{
    using System;
    using System.Collections.Generic;
    
    public partial class encyclopedia
    {
        public int Encyclopedia_id { get; set; }
        public int Fish_Id { get; set; }
        public int User_id { get; set; }
    
        public virtual Fish Fish { get; set; }
        public virtual User User { get; set; }
    }
}
