//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishGuide
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fish()
        {
            this.encyclopedia = new HashSet<encyclopedia>();
        }
    
        public int Fish_id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Tackle { get; set; }
        public string Area { get; set; }
        public string Season { get; set; }
        public string About { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encyclopedia> encyclopedia { get; set; }
        public virtual Tackle Tackle1 { get; set; }
    }
}
