//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishGuide
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> Recipe_id { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
